
export default {
Brand: require('./schemas/Brand.json'),
ContactPoint: require('./schemas/ContactPoint.json'),
CovidTestPassEvidenceDocument: require('./schemas/CovidTestPassEvidenceDocument.json'),
CovidTestPassStandardCredentialDetailed: require('./schemas/CovidTestPassStandardCredentialDetailed.json'),
CovidTestPassStandardCredentialMinimal: require('./schemas/CovidTestPassStandardCredentialMinimal.json'),
CovidTestRegistrationCredential: require('./schemas/CovidTestRegistrationCredential.json'),
DGCInfectionInformation: require('./schemas/DGCInfectionInformation.json'),
DGCProofOfCovidTest: require('./schemas/DGCProofOfCovidTest.json'),
DGCProofOfRecovery: require('./schemas/DGCProofOfRecovery.json'),
DGCProofOfVaccination: require('./schemas/DGCProofOfVaccination.json'),
DGCSubject: require('./schemas/DGCSubject.json'),
DGCTestInformation: require('./schemas/DGCTestInformation.json'),
DGCVaccinationInformation: require('./schemas/DGCVaccinationInformation.json'),
DGCVaccine: require('./schemas/DGCVaccine.json'),
Entity: require('./schemas/Entity.json'),
GeoCoordinates: require('./schemas/GeoCoordinates.json'),
LEIaddress: require('./schemas/LEIaddress.json'),
LEIauthority: require('./schemas/LEIauthority.json'),
LEIentity: require('./schemas/LEIentity.json'),
LEIevidenceDocument: require('./schemas/LEIevidenceDocument.json'),
LEIregistration: require('./schemas/LEIregistration.json'),
LegalEntityIdentifierCredential: require('./schemas/LegalEntityIdentifierCredential.json'),
MedicalTest: require('./schemas/MedicalTest.json'),
Organization: require('./schemas/Organization.json'),
Person: require('./schemas/Person.json'),
Place: require('./schemas/Place.json'),
PostalAddress: require('./schemas/PostalAddress.json'),
PriceSpecification: require('./schemas/PriceSpecification.json'),
Product: require('./schemas/Product.json'),
ProductRegistrationEvidenceDocument: require('./schemas/ProductRegistrationEvidenceDocument.json'),
QuantitativeValue: require('./schemas/QuantitativeValue.json'),
TotalCharge: require('./schemas/TotalCharge.json'),
chargeAndPaymentType: require('./schemas/chargeAndPaymentType.json'),
}
